mode con cp select=1252 > nul
if not exist "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\lib\%4" mkdir "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\lib\%4"
if not exist "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib" mkdir "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib"
if not exist "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core" mkdir "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core"
if not exist "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\CSS" mkdir "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\CSS"
if not exist "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\IOData" mkdir "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\IOData"
if not exist "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Math" mkdir "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Math"
if not exist "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Resources" mkdir "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Resources"
if not exist "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Signals" mkdir "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Signals"
if not exist "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\System" mkdir "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\System"
if not exist "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Text" mkdir "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Text"
if not exist "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\XML" mkdir "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\XML"
if not exist "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Zip" mkdir "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Zip"
copy "..\Sources\API\core.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\core.h" > nul
copy "..\Sources\API\Core\api_core.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\api_core.h" > nul
copy "..\Sources\API\Core\core_iostream.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\core_iostream.h" > nul
copy "..\Sources\API\Core\CSS\css_document.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\CSS\css_document.h" > nul
copy "..\Sources\API\Core\CSS\css_property.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\CSS\css_property.h" > nul
copy "..\Sources\API\Core\CSS\css_token.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\CSS\css_token.h" > nul
copy "..\Sources\API\Core\CSS\css_tokenizer.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\CSS\css_tokenizer.h" > nul
copy "..\Sources\API\Core\IOData\access_control_list.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\IOData\access_control_list.h" > nul
copy "..\Sources\API\Core\IOData\cl_endian.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\IOData\cl_endian.h" > nul
copy "..\Sources\API\Core\IOData\datatypes.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\IOData\datatypes.h" > nul
copy "..\Sources\API\Core\IOData\directory.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\IOData\directory.h" > nul
copy "..\Sources\API\Core\IOData\directory_scanner.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\IOData\directory_scanner.h" > nul
copy "..\Sources\API\Core\IOData\file.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\IOData\file.h" > nul
copy "..\Sources\API\Core\IOData\file_help.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\IOData\file_help.h" > nul
copy "..\Sources\API\Core\IOData\iodevice.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\IOData\iodevice.h" > nul
copy "..\Sources\API\Core\IOData\iodevice_memory.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\IOData\iodevice_memory.h" > nul
copy "..\Sources\API\Core\IOData\iodevice_provider.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\IOData\iodevice_provider.h" > nul
copy "..\Sources\API\Core\IOData\path_help.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\IOData\path_help.h" > nul
copy "..\Sources\API\Core\IOData\pipe_connection.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\IOData\pipe_connection.h" > nul
copy "..\Sources\API\Core\IOData\pipe_listen.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\IOData\pipe_listen.h" > nul
copy "..\Sources\API\Core\IOData\security_descriptor.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\IOData\security_descriptor.h" > nul
copy "..\Sources\API\Core\IOData\security_identifier.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\IOData\security_identifier.h" > nul
copy "..\Sources\API\Core\IOData\virtual_directory.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\IOData\virtual_directory.h" > nul
copy "..\Sources\API\Core\IOData\virtual_directory_listing.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\IOData\virtual_directory_listing.h" > nul
copy "..\Sources\API\Core\IOData\virtual_directory_listing_entry.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\IOData\virtual_directory_listing_entry.h" > nul
copy "..\Sources\API\Core\IOData\virtual_file_source.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\IOData\virtual_file_source.h" > nul
copy "..\Sources\API\Core\IOData\virtual_file_system.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\IOData\virtual_file_system.h" > nul
copy "..\Sources\API\Core\Math\angle.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Math\angle.h" > nul
copy "..\Sources\API\Core\Math\base64_decoder.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Math\base64_decoder.h" > nul
copy "..\Sources\API\Core\Math\base64_encoder.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Math\base64_encoder.h" > nul
copy "..\Sources\API\Core\Math\bezier_curve.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Math\bezier_curve.h" > nul
copy "..\Sources\API\Core\Math\circle.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Math\circle.h" > nul
copy "..\Sources\API\Core\Math\cl_math.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Math\cl_math.h" > nul
copy "..\Sources\API\Core\Math\delauney_triangulator.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Math\delauney_triangulator.h" > nul
copy "..\Sources\API\Core\Math\ear_clip_result.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Math\ear_clip_result.h" > nul
copy "..\Sources\API\Core\Math\ear_clip_triangulator.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Math\ear_clip_triangulator.h" > nul
copy "..\Sources\API\Core\Math\hash_functions.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Math\hash_functions.h" > nul
copy "..\Sources\API\Core\Math\line.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Math\line.h" > nul
copy "..\Sources\API\Core\Math\line_math.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Math\line_math.h" > nul
copy "..\Sources\API\Core\Math\line_ray.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Math\line_ray.h" > nul
copy "..\Sources\API\Core\Math\line_segment.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Math\line_segment.h" > nul
copy "..\Sources\API\Core\Math\mat2.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Math\mat2.h" > nul
copy "..\Sources\API\Core\Math\mat3.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Math\mat3.h" > nul
copy "..\Sources\API\Core\Math\mat4.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Math\mat4.h" > nul
copy "..\Sources\API\Core\Math\origin.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Math\origin.h" > nul
copy "..\Sources\API\Core\Math\outline_triangulator.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Math\outline_triangulator.h" > nul
copy "..\Sources\API\Core\Math\point.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Math\point.h" > nul
copy "..\Sources\API\Core\Math\pointset_math.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Math\pointset_math.h" > nul
copy "..\Sources\API\Core\Math\quad.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Math\quad.h" > nul
copy "..\Sources\API\Core\Math\quaternion.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Math\quaternion.h" > nul
copy "..\Sources\API\Core\Math\rect.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Math\rect.h" > nul
copy "..\Sources\API\Core\Math\rect_packer.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Math\rect_packer.h" > nul
copy "..\Sources\API\Core\Math\sha1.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Math\sha1.h" > nul
copy "..\Sources\API\Core\Math\size.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Math\size.h" > nul
copy "..\Sources\API\Core\Math\triangle_math.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Math\triangle_math.h" > nul
copy "..\Sources\API\Core\Math\vec1.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Math\vec1.h" > nul
copy "..\Sources\API\Core\Math\vec2.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Math\vec2.h" > nul
copy "..\Sources\API\Core\Math\vec3.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Math\vec3.h" > nul
copy "..\Sources\API\Core\Math\vec4.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Math\vec4.h" > nul
copy "..\Sources\API\Core\Resources\resource.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Resources\resource.h" > nul
copy "..\Sources\API\Core\Resources\resource_data_session.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Resources\resource_data_session.h" > nul
copy "..\Sources\API\Core\Resources\resource_manager.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Resources\resource_manager.h" > nul
copy "..\Sources\API\Core\Signals\callback_0.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Signals\callback_0.h" > nul
copy "..\Sources\API\Core\Signals\callback_1.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Signals\callback_1.h" > nul
copy "..\Sources\API\Core\Signals\callback_2.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Signals\callback_2.h" > nul
copy "..\Sources\API\Core\Signals\callback_3.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Signals\callback_3.h" > nul
copy "..\Sources\API\Core\Signals\callback_4.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Signals\callback_4.h" > nul
copy "..\Sources\API\Core\Signals\callback_5.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Signals\callback_5.h" > nul
copy "..\Sources\API\Core\Signals\callback_v0.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Signals\callback_v0.h" > nul
copy "..\Sources\API\Core\Signals\callback_v1.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Signals\callback_v1.h" > nul
copy "..\Sources\API\Core\Signals\callback_v2.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Signals\callback_v2.h" > nul
copy "..\Sources\API\Core\Signals\callback_v3.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Signals\callback_v3.h" > nul
copy "..\Sources\API\Core\Signals\callback_v4.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Signals\callback_v4.h" > nul
copy "..\Sources\API\Core\Signals\callback_v5.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Signals\callback_v5.h" > nul
copy "..\Sources\API\Core\Signals\signals_impl.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Signals\signals_impl.h" > nul
copy "..\Sources\API\Core\Signals\signal_v0.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Signals\signal_v0.h" > nul
copy "..\Sources\API\Core\Signals\signal_v1.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Signals\signal_v1.h" > nul
copy "..\Sources\API\Core\Signals\signal_v2.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Signals\signal_v2.h" > nul
copy "..\Sources\API\Core\Signals\signal_v3.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Signals\signal_v3.h" > nul
copy "..\Sources\API\Core\Signals\signal_v4.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Signals\signal_v4.h" > nul
copy "..\Sources\API\Core\Signals\signal_v5.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Signals\signal_v5.h" > nul
copy "..\Sources\API\Core\Signals\slot.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Signals\slot.h" > nul
copy "..\Sources\API\Core\Signals\slot_container.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Signals\slot_container.h" > nul
copy "..\Sources\API\Core\Signals\virtual_function_0.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Signals\virtual_function_0.h" > nul
copy "..\Sources\API\Core\Signals\virtual_function_1.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Signals\virtual_function_1.h" > nul
copy "..\Sources\API\Core\Signals\virtual_function_2.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Signals\virtual_function_2.h" > nul
copy "..\Sources\API\Core\Signals\virtual_function_3.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Signals\virtual_function_3.h" > nul
copy "..\Sources\API\Core\Signals\virtual_function_4.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Signals\virtual_function_4.h" > nul
copy "..\Sources\API\Core\Signals\virtual_function_5.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Signals\virtual_function_5.h" > nul
copy "..\Sources\API\Core\Signals\virtual_function_v0.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Signals\virtual_function_v0.h" > nul
copy "..\Sources\API\Core\Signals\virtual_function_v1.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Signals\virtual_function_v1.h" > nul
copy "..\Sources\API\Core\Signals\virtual_function_v2.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Signals\virtual_function_v2.h" > nul
copy "..\Sources\API\Core\Signals\virtual_function_v3.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Signals\virtual_function_v3.h" > nul
copy "..\Sources\API\Core\Signals\virtual_function_v4.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Signals\virtual_function_v4.h" > nul
copy "..\Sources\API\Core\Signals\virtual_function_v5.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Signals\virtual_function_v5.h" > nul
copy "..\Sources\API\Core\System\autoptr.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\System\autoptr.h" > nul
copy "..\Sources\API\Core\System\block_allocator.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\System\block_allocator.h" > nul
copy "..\Sources\API\Core\System\command_line.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\System\command_line.h" > nul
copy "..\Sources\API\Core\System\comptr.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\System\comptr.h" > nul
copy "..\Sources\API\Core\System\console_window.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\System\console_window.h" > nul
copy "..\Sources\API\Core\System\databuffer.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\System\databuffer.h" > nul
copy "..\Sources\API\Core\System\datetime.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\System\datetime.h" > nul
copy "..\Sources\API\Core\System\disposable_object.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\System\disposable_object.h" > nul
copy "..\Sources\API\Core\System\event.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\System\event.h" > nul
copy "..\Sources\API\Core\System\event_provider.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\System\event_provider.h" > nul
copy "..\Sources\API\Core\System\exception.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\System\exception.h" > nul
copy "..\Sources\API\Core\System\fixed_memory_pool.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\System\fixed_memory_pool.h" > nul
copy "..\Sources\API\Core\System\interlocked_variable.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\System\interlocked_variable.h" > nul
copy "..\Sources\API\Core\System\keep_alive.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\System\keep_alive.h" > nul
copy "..\Sources\API\Core\System\memory_pool.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\System\memory_pool.h" > nul
copy "..\Sources\API\Core\System\mutex.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\System\mutex.h" > nul
copy "..\Sources\API\Core\System\registry_key.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\System\registry_key.h" > nul
copy "..\Sources\API\Core\System\runnable.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\System\runnable.h" > nul
copy "..\Sources\API\Core\System\service.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\System\service.h" > nul
copy "..\Sources\API\Core\System\setup_core.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\System\setup_core.h" > nul
copy "..\Sources\API\Core\System\sharedptr.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\System\sharedptr.h" > nul
copy "..\Sources\API\Core\System\static_memory_pool.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\System\static_memory_pool.h" > nul
copy "..\Sources\API\Core\System\system.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\System\system.h" > nul
copy "..\Sources\API\Core\System\thread.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\System\thread.h" > nul
copy "..\Sources\API\Core\System\thread_local_storage.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\System\thread_local_storage.h" > nul
copy "..\Sources\API\Core\System\timer.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\System\timer.h" > nul
copy "..\Sources\API\Core\System\weakptr.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\System\weakptr.h" > nul
copy "..\Sources\API\Core\Text\console.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Text\console.h" > nul
copy "..\Sources\API\Core\Text\console_logger.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Text\console_logger.h" > nul
copy "..\Sources\API\Core\Text\file_logger.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Text\file_logger.h" > nul
copy "..\Sources\API\Core\Text\logger.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Text\logger.h" > nul
copy "..\Sources\API\Core\Text\string16.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Text\string16.h" > nul
copy "..\Sources\API\Core\Text\string8.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Text\string8.h" > nul
copy "..\Sources\API\Core\Text\string_allocator.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Text\string_allocator.h" > nul
copy "..\Sources\API\Core\Text\string_data16.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Text\string_data16.h" > nul
copy "..\Sources\API\Core\Text\string_data8.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Text\string_data8.h" > nul
copy "..\Sources\API\Core\Text\string_format.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Text\string_format.h" > nul
copy "..\Sources\API\Core\Text\string_help.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Text\string_help.h" > nul
copy "..\Sources\API\Core\Text\string_ref16.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Text\string_ref16.h" > nul
copy "..\Sources\API\Core\Text\string_ref8.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Text\string_ref8.h" > nul
copy "..\Sources\API\Core\Text\string_types.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Text\string_types.h" > nul
copy "..\Sources\API\Core\Text\utf8_reader.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Text\utf8_reader.h" > nul
copy "..\Sources\API\Core\XML\dom_attr.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\XML\dom_attr.h" > nul
copy "..\Sources\API\Core\XML\dom_cdata_section.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\XML\dom_cdata_section.h" > nul
copy "..\Sources\API\Core\XML\dom_character_data.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\XML\dom_character_data.h" > nul
copy "..\Sources\API\Core\XML\dom_comment.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\XML\dom_comment.h" > nul
copy "..\Sources\API\Core\XML\dom_document.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\XML\dom_document.h" > nul
copy "..\Sources\API\Core\XML\dom_document_fragment.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\XML\dom_document_fragment.h" > nul
copy "..\Sources\API\Core\XML\dom_document_type.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\XML\dom_document_type.h" > nul
copy "..\Sources\API\Core\XML\dom_element.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\XML\dom_element.h" > nul
copy "..\Sources\API\Core\XML\dom_entity.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\XML\dom_entity.h" > nul
copy "..\Sources\API\Core\XML\dom_entity_reference.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\XML\dom_entity_reference.h" > nul
copy "..\Sources\API\Core\XML\dom_exception.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\XML\dom_exception.h" > nul
copy "..\Sources\API\Core\XML\dom_implementation.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\XML\dom_implementation.h" > nul
copy "..\Sources\API\Core\XML\dom_named_node_map.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\XML\dom_named_node_map.h" > nul
copy "..\Sources\API\Core\XML\dom_node.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\XML\dom_node.h" > nul
copy "..\Sources\API\Core\XML\dom_node_list.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\XML\dom_node_list.h" > nul
copy "..\Sources\API\Core\XML\dom_notation.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\XML\dom_notation.h" > nul
copy "..\Sources\API\Core\XML\dom_processing_instruction.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\XML\dom_processing_instruction.h" > nul
copy "..\Sources\API\Core\XML\dom_string.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\XML\dom_string.h" > nul
copy "..\Sources\API\Core\XML\dom_text.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\XML\dom_text.h" > nul
copy "..\Sources\API\Core\XML\xml_token.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\XML\xml_token.h" > nul
copy "..\Sources\API\Core\XML\xml_tokenizer.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\XML\xml_tokenizer.h" > nul
copy "..\Sources\API\Core\XML\xml_writer.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\XML\xml_writer.h" > nul
copy "..\Sources\API\Core\XML\xpath_evaluator.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\XML\xpath_evaluator.h" > nul
copy "..\Sources\API\Core\XML\xpath_object.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\XML\xpath_object.h" > nul
copy "..\Sources\API\Core\Zip\zip_archive.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Zip\zip_archive.h" > nul
copy "..\Sources\API\Core\Zip\zip_file_entry.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Zip\zip_file_entry.h" > nul
copy "..\Sources\API\Core\Zip\zip_reader.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Zip\zip_reader.h" > nul
copy "..\Sources\API\Core\Zip\zip_writer.h" "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\include\ClanLib\Core\Zip\zip_writer.h" > nul
copy %1 "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\lib\%4" > nul
copy %2 "C:\Paal\Development\Games\HiN-SimViz\HiN-SimViz\Src\Depends\ClanLib\lib\%4\%3" > nul
